# Generated by Django 4.0.4 on 2022-05-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_diagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alert', models.BooleanField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_diagram.state')),
            ],
        ),
    ]
